// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODLAPI.Models;

#nullable disable

namespace ODLAPI.Migrations
{
    [DbContext(typeof(TriggerDBContext))]
    [Migration("20221021154748_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODLAPI.Models.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InputFileName")
                        .HasColumnType("text");

                    b.Property<string>("NumberOfRows")
                        .HasColumnType("text");

                    b.Property<string>("OutputFileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
